"""estrutura inicial

Revision ID: 18211820b0bf
Revises: 
Create Date: 2026-08-25 15:10:59.555680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18211820b0bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biomas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('clima', sa.String(length=50), nullable=True),
    sa.Column('vegetacao', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('especies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_popular', sa.String(length=100), nullable=False),
    sa.Column('nome_cientifico', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_especies_usuario_id'), 'especies', ['usuario_id'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=64), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_codigo'), 'tokens', ['codigo'], unique=True)
    op.create_index(op.f('ix_tokens_usuario_id'), 'tokens', ['usuario_id'], unique=False)
    op.create_table('animais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dieta', sa.String(length=50), nullable=False),
    sa.Column('habitat_especifico', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['especies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('especie_bioma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('especie_id', sa.Integer(), nullable=False),
    sa.Column('bioma_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bioma_id'], ['biomas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['especie_id'], ['especies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('especie_id', 'bioma_id', name='uq_especie_bioma')
    )
    op.create_index(op.f('ix_especie_bioma_bioma_id'), 'especie_bioma', ['bioma_id'], unique=False)
    op.create_index(op.f('ix_especie_bioma_especie_id'), 'especie_bioma', ['especie_id'], unique=False)
    op.create_table('participantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participantes_token_id'), 'participantes', ['token_id'], unique=False)
    op.create_table('plantas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_folha', sa.String(length=50), nullable=False),
    sa.Column('medicinal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['especies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plantas')
    op.drop_index(op.f('ix_participantes_token_id'), table_name='participantes')
    op.drop_table('participantes')
    op.drop_index(op.f('ix_especie_bioma_especie_id'), table_name='especie_bioma')
    op.drop_index(op.f('ix_especie_bioma_bioma_id'), table_name='especie_bioma')
    op.drop_table('especie_bioma')
    op.drop_table('animais')
    op.drop_index(op.f('ix_tokens_usuario_id'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_codigo'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_especies_usuario_id'), table_name='especies')
    op.drop_table('especies')
    op.drop_table('usuarios')
    op.drop_table('biomas')
    # ### end Alembic commands ###
