"""ajusta indices de usuarios e tokens

Revision ID: c7d0a27085e5
Revises: a246d60040e1
Create Date: 2026-08-25 21:18:42.030449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d0a27085e5'
down_revision: Union[str, Sequence[str], None] = 'a246d60040e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tokens_expira_em'), 'tokens', ['expira_em'], unique=False)
    op.drop_index(op.f('email'), table_name='usuarios')
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.create_index(op.f('email'), 'usuarios', ['email'], unique=True)
    op.drop_index(op.f('ix_tokens_expira_em'), table_name='tokens')
    # ### end Alembic commands ###
